use [RentApartments]
go

--Insert countries
INSERT INTO _Country(IsoCode, Name) VALUES ('AU', 'Australia');
INSERT INTO _Country(IsoCode, Name) VALUES ('AT', 'Austria');
INSERT INTO _Country(IsoCode, Name) VALUES ('AZ', 'Azerbaijan');
INSERT INTO _Country(IsoCode, Name) VALUES ('BS', 'Bahamas');
INSERT INTO _Country(IsoCode, Name) VALUES ('BH', 'Bahrain');
INSERT INTO _Country(IsoCode, Name) VALUES ('BD', 'Bangladesh');
INSERT INTO _Country(IsoCode, Name) VALUES ('BB', 'Barbados');
INSERT INTO _Country(IsoCode, Name) VALUES ('BY', 'Belarus');
INSERT INTO _Country(IsoCode, Name) VALUES ('BE', 'Belgium');
INSERT INTO _Country(IsoCode, Name) VALUES ('BZ', 'Belize');
INSERT INTO _Country(IsoCode, Name) VALUES ('BJ', 'Benin');
INSERT INTO _Country(IsoCode, Name) VALUES ('BM', 'Bermuda');
INSERT INTO _Country(IsoCode, Name) VALUES ('BT', 'Bhutan');
INSERT INTO _Country(IsoCode, Name) VALUES ('BO', 'Bolivia');
INSERT INTO _Country(IsoCode, Name) VALUES ('BA', 'Bosnia and Herzegovina');
INSERT INTO _Country(IsoCode, Name) VALUES ('BW', 'Botswana');
INSERT INTO _Country(IsoCode, Name) VALUES ('BV', 'Bouvet Island');
INSERT INTO _Country(IsoCode, Name) VALUES ('BR', 'Brazil');
INSERT INTO _Country(IsoCode, Name) VALUES ('BQ', 'British Antarctic Territory');
INSERT INTO _Country(IsoCode, Name) VALUES ('IO', 'British Indian Ocean Territory');
INSERT INTO _Country(IsoCode, Name) VALUES ('VG', 'British Virgin Islands');
INSERT INTO _Country(IsoCode, Name) VALUES ('BN', 'Brunei');
INSERT INTO _Country(IsoCode, Name) VALUES ('BG', 'Bulgaria');
INSERT INTO _Country(IsoCode, Name) VALUES ('BF', 'Burkina Faso');
INSERT INTO _Country(IsoCode, Name) VALUES ('BI', 'Burundi');
INSERT INTO _Country(IsoCode, Name) VALUES ('KH', 'Cambodia');
INSERT INTO _Country(IsoCode, Name) VALUES ('CM', 'Cameroon');
INSERT INTO _Country(IsoCode, Name) VALUES ('CA', 'Canada');
INSERT INTO _Country(IsoCode, Name) VALUES ('CT', 'Canton and Enderbury Islands');
INSERT INTO _Country(IsoCode, Name) VALUES ('CV', 'Cape Verde');
INSERT INTO _Country(IsoCode, Name) VALUES ('KY', 'Cayman Islands');
INSERT INTO _Country(IsoCode, Name) VALUES ('CF', 'Central African Republic');
INSERT INTO _Country(IsoCode, Name) VALUES ('TD', 'Chad');
INSERT INTO _Country(IsoCode, Name) VALUES ('CL', 'Chile');
INSERT INTO _Country(IsoCode, Name) VALUES ('CN', 'China');
INSERT INTO _Country(IsoCode, Name) VALUES ('CX', 'Christmas Island');
INSERT INTO _Country(IsoCode, Name) VALUES ('CC', 'Cocos [Keeling] Islands');
INSERT INTO _Country(IsoCode, Name) VALUES ('CO', 'Colombia');
INSERT INTO _Country(IsoCode, Name) VALUES ('KM', 'Comoros');
INSERT INTO _Country(IsoCode, Name) VALUES ('CG', 'Congo - Brazzaville');
INSERT INTO _Country(IsoCode, Name) VALUES ('CD', 'Congo - Kinshasa');
INSERT INTO _Country(IsoCode, Name) VALUES ('CK', 'Cook Islands');
INSERT INTO _Country(IsoCode, Name) VALUES ('CR', 'Costa Rica');
INSERT INTO _Country(IsoCode, Name) VALUES ('HR', 'Croatia');
INSERT INTO _Country(IsoCode, Name) VALUES ('CU', 'Cuba');
INSERT INTO _Country(IsoCode, Name) VALUES ('CY', 'Cyprus');
INSERT INTO _Country(IsoCode, Name) VALUES ('CZ', 'Czech Republic');
INSERT INTO _Country(IsoCode, Name) VALUES ('CI', 'Côte d’Ivoire');
INSERT INTO _Country(IsoCode, Name) VALUES ('DK', 'Denmark');
INSERT INTO _Country(IsoCode, Name) VALUES ('DJ', 'Djibouti');
INSERT INTO _Country(IsoCode, Name) VALUES ('DM', 'Dominica');
INSERT INTO _Country(IsoCode, Name) VALUES ('DO', 'Dominican Republic');
INSERT INTO _Country(IsoCode, Name) VALUES ('NQ', 'Dronning Maud Land');
INSERT INTO _Country(IsoCode, Name) VALUES ('DD', 'East Germany');
INSERT INTO _Country(IsoCode, Name) VALUES ('EC', 'Ecuador');
INSERT INTO _Country(IsoCode, Name) VALUES ('EG', 'Egypt');
INSERT INTO _Country(IsoCode, Name) VALUES ('SV', 'El Salvador');
INSERT INTO _Country(IsoCode, Name) VALUES ('GQ', 'Equatorial Guinea');
INSERT INTO _Country(IsoCode, Name) VALUES ('ER', 'Eritrea');
INSERT INTO _Country(IsoCode, Name) VALUES ('EE', 'Estonia');
INSERT INTO _Country(IsoCode, Name) VALUES ('ET', 'Ethiopia');
INSERT INTO _Country(IsoCode, Name) VALUES ('FK', 'Falkland Islands');
INSERT INTO _Country(IsoCode, Name) VALUES ('FO', 'Faroe Islands');
INSERT INTO _Country(IsoCode, Name) VALUES ('FJ', 'Fiji');
INSERT INTO _Country(IsoCode, Name) VALUES ('FI', 'Finland');
INSERT INTO _Country(IsoCode, Name) VALUES ('FR', 'France');
INSERT INTO _Country(IsoCode, Name) VALUES ('GF', 'French Guiana');
INSERT INTO _Country(IsoCode, Name) VALUES ('PF', 'French Polynesia');
INSERT INTO _Country(IsoCode, Name) VALUES ('TF', 'French Southern Territories');
INSERT INTO _Country(IsoCode, Name) VALUES ('FQ', 'French Southern and Antarctic Territories');
INSERT INTO _Country(IsoCode, Name) VALUES ('GA', 'Gabon');
INSERT INTO _Country(IsoCode, Name) VALUES ('GM', 'Gambia');
INSERT INTO _Country(IsoCode, Name) VALUES ('GE', 'Georgia');
INSERT INTO _Country(IsoCode, Name) VALUES ('DE', 'Germany');
INSERT INTO _Country(IsoCode, Name) VALUES ('GH', 'Ghana');
INSERT INTO _Country(IsoCode, Name) VALUES ('GI', 'Gibraltar');
INSERT INTO _Country(IsoCode, Name) VALUES ('GR', 'Greece');
INSERT INTO _Country(IsoCode, Name) VALUES ('GL', 'Greenland');
INSERT INTO _Country(IsoCode, Name) VALUES ('GD', 'Grenada');
INSERT INTO _Country(IsoCode, Name) VALUES ('GP', 'Guadeloupe');
INSERT INTO _Country(IsoCode, Name) VALUES ('GU', 'Guam');
INSERT INTO _Country(IsoCode, Name) VALUES ('GT', 'Guatemala');
INSERT INTO _Country(IsoCode, Name) VALUES ('GG', 'Guernsey');
INSERT INTO _Country(IsoCode, Name) VALUES ('GN', 'Guinea');
INSERT INTO _Country(IsoCode, Name) VALUES ('GW', 'Guinea-Bissau');
INSERT INTO _Country(IsoCode, Name) VALUES ('GY', 'Guyana');
INSERT INTO _Country(IsoCode, Name) VALUES ('HT', 'Haiti');
INSERT INTO _Country(IsoCode, Name) VALUES ('HM', 'Heard Island and McDonald Islands');
INSERT INTO _Country(IsoCode, Name) VALUES ('HN', 'Honduras');
INSERT INTO _Country(IsoCode, Name) VALUES ('HK', 'Hong Kong SAR China');
INSERT INTO _Country(IsoCode, Name) VALUES ('HU', 'Hungary');
INSERT INTO _Country(IsoCode, Name) VALUES ('IS', 'Iceland');
INSERT INTO _Country(IsoCode, Name) VALUES ('IN', 'India');
INSERT INTO _Country(IsoCode, Name) VALUES ('ID', 'Indonesia');
INSERT INTO _Country(IsoCode, Name) VALUES ('IR', 'Iran');
INSERT INTO _Country(IsoCode, Name) VALUES ('IQ', 'Iraq');
INSERT INTO _Country(IsoCode, Name) VALUES ('IE', 'Ireland');
INSERT INTO _Country(IsoCode, Name) VALUES ('IM', 'Isle of Man');
INSERT INTO _Country(IsoCode, Name) VALUES ('IL', 'Israel');
INSERT INTO _Country(IsoCode, Name) VALUES ('IT', 'Italy');
INSERT INTO _Country(IsoCode, Name) VALUES ('JM', 'Jamaica');
INSERT INTO _Country(IsoCode, Name) VALUES ('JP', 'Japan');
INSERT INTO _Country(IsoCode, Name) VALUES ('JE', 'Jersey');
INSERT INTO _Country(IsoCode, Name) VALUES ('JT', 'Johnston Island');
INSERT INTO _Country(IsoCode, Name) VALUES ('JO', 'Jordan');
INSERT INTO _Country(IsoCode, Name) VALUES ('KZ', 'Kazakhstan');
INSERT INTO _Country(IsoCode, Name) VALUES ('KE', 'Kenya');
INSERT INTO _Country(IsoCode, Name) VALUES ('KI', 'Kiribati');
INSERT INTO _Country(IsoCode, Name) VALUES ('KW', 'Kuwait');
INSERT INTO _Country(IsoCode, Name) VALUES ('KG', 'Kyrgyzstan');
INSERT INTO _Country(IsoCode, Name) VALUES ('LA', 'Laos');
INSERT INTO _Country(IsoCode, Name) VALUES ('LV', 'Latvia');
INSERT INTO _Country(IsoCode, Name) VALUES ('LB', 'Lebanon');
INSERT INTO _Country(IsoCode, Name) VALUES ('LS', 'Lesotho');
INSERT INTO _Country(IsoCode, Name) VALUES ('LR', 'Liberia');
INSERT INTO _Country(IsoCode, Name) VALUES ('LY', 'Libya');
INSERT INTO _Country(IsoCode, Name) VALUES ('LI', 'Liechtenstein');
INSERT INTO _Country(IsoCode, Name) VALUES ('LT', 'Lithuania');
INSERT INTO _Country(IsoCode, Name) VALUES ('LU', 'Luxembourg');
INSERT INTO _Country(IsoCode, Name) VALUES ('MO', 'Macau SAR China');
INSERT INTO _Country(IsoCode, Name) VALUES ('MK', 'Macedonia');
INSERT INTO _Country(IsoCode, Name) VALUES ('MG', 'Madagascar');
INSERT INTO _Country(IsoCode, Name) VALUES ('MW', 'Malawi');
INSERT INTO _Country(IsoCode, Name) VALUES ('MY', 'Malaysia');
INSERT INTO _Country(IsoCode, Name) VALUES ('MV', 'Maldives');
INSERT INTO _Country(IsoCode, Name) VALUES ('ML', 'Mali');
INSERT INTO _Country(IsoCode, Name) VALUES ('MT', 'Malta');
INSERT INTO _Country(IsoCode, Name) VALUES ('MH', 'Marshall Islands');
INSERT INTO _Country(IsoCode, Name) VALUES ('MQ', 'Martinique');
INSERT INTO _Country(IsoCode, Name) VALUES ('MR', 'Mauritania');
INSERT INTO _Country(IsoCode, Name) VALUES ('MU', 'Mauritius');
INSERT INTO _Country(IsoCode, Name) VALUES ('YT', 'Mayotte');
INSERT INTO _Country(IsoCode, Name) VALUES ('FX', 'Metropolitan France');
INSERT INTO _Country(IsoCode, Name) VALUES ('MX', 'Mexico');
INSERT INTO _Country(IsoCode, Name) VALUES ('FM', 'Micronesia');
INSERT INTO _Country(IsoCode, Name) VALUES ('MI', 'Midway Islands');
INSERT INTO _Country(IsoCode, Name) VALUES ('MD', 'Moldova');
INSERT INTO _Country(IsoCode, Name) VALUES ('MC', 'Monaco');
INSERT INTO _Country(IsoCode, Name) VALUES ('MN', 'Mongolia');
INSERT INTO _Country(IsoCode, Name) VALUES ('ME', 'Montenegro');
INSERT INTO _Country(IsoCode, Name) VALUES ('MS', 'Montserrat');
INSERT INTO _Country(IsoCode, Name) VALUES ('MA', 'Morocco');
INSERT INTO _Country(IsoCode, Name) VALUES ('MZ', 'Mozambique');
INSERT INTO _Country(IsoCode, Name) VALUES ('MM', 'Myanmar [Burma]');
INSERT INTO _Country(IsoCode, Name) VALUES ('NA', 'Namibia');
INSERT INTO _Country(IsoCode, Name) VALUES ('NR', 'Nauru');
INSERT INTO _Country(IsoCode, Name) VALUES ('NP', 'Nepal');
INSERT INTO _Country(IsoCode, Name) VALUES ('NL', 'Netherlands');
INSERT INTO _Country(IsoCode, Name) VALUES ('NZ', 'New Zealand');
INSERT INTO _Country(IsoCode, Name) VALUES ('NO', 'Norway');
INSERT INTO _Country(IsoCode, Name) VALUES ('PC', 'Pacific Islands Trust Territory');
INSERT INTO _Country(IsoCode, Name) VALUES ('PA', 'Panama');
INSERT INTO _Country(IsoCode, Name) VALUES ('PG', 'Papua New Guinea');
INSERT INTO _Country(IsoCode, Name) VALUES ('PY', 'Paraguay');
INSERT INTO _Country(IsoCode, Name) VALUES ('PE', 'Peru');
INSERT INTO _Country(IsoCode, Name) VALUES ('PH', 'Philippines');
INSERT INTO _Country(IsoCode, Name) VALUES ('PN', 'Pitcairn Islands');
INSERT INTO _Country(IsoCode, Name) VALUES ('PL', 'Poland');
INSERT INTO _Country(IsoCode, Name) VALUES ('PT', 'Portugal');
INSERT INTO _Country(IsoCode, Name) VALUES ('PR', 'Puerto Rico');
INSERT INTO _Country(IsoCode, Name) VALUES ('QA', 'Qatar');
INSERT INTO _Country(IsoCode, Name) VALUES ('RO', 'Romania');
INSERT INTO _Country(IsoCode, Name) VALUES ('RU', 'Russia');
INSERT INTO _Country(IsoCode, Name) VALUES ('SM', 'San Marino');
INSERT INTO _Country(IsoCode, Name) VALUES ('SA', 'Saudi Arabia');
INSERT INTO _Country(IsoCode, Name) VALUES ('RS', 'Serbia');
INSERT INTO _Country(IsoCode, Name) VALUES ('CS', 'Serbia and Montenegro');
INSERT INTO _Country(IsoCode, Name) VALUES ('SG', 'Singapore');
INSERT INTO _Country(IsoCode, Name) VALUES ('SK', 'Slovakia');
INSERT INTO _Country(IsoCode, Name) VALUES ('SI', 'Slovenia');
INSERT INTO _Country(IsoCode, Name) VALUES ('ZA', 'South Africa');
INSERT INTO _Country(IsoCode, Name) VALUES ('ES', 'Spain');
INSERT INTO _Country(IsoCode, Name) VALUES ('SE', 'Sweden');
INSERT INTO _Country(IsoCode, Name) VALUES ('CH', 'Switzerland');
INSERT INTO _Country(IsoCode, Name) VALUES ('TW', 'Taiwan');
INSERT INTO _Country(IsoCode, Name) VALUES ('TJ', 'Tajikistan');
INSERT INTO _Country(IsoCode, Name) VALUES ('TH', 'Thailand');
INSERT INTO _Country(IsoCode, Name) VALUES ('TN', 'Tunisia');
INSERT INTO _Country(IsoCode, Name) VALUES ('TR', 'Turkey');
INSERT INTO _Country(IsoCode, Name) VALUES ('TM', 'Turkmenistan');
INSERT INTO _Country(IsoCode, Name) VALUES ('UM', 'U.S. Minor Outlying Islands');
INSERT INTO _Country(IsoCode, Name) VALUES ('PU', 'U.S. Miscellaneous Pacific Islands');
INSERT INTO _Country(IsoCode, Name) VALUES ('VI', 'U.S. Virgin Islands');
INSERT INTO _Country(IsoCode, Name) VALUES ('UA', 'Ukraine');
INSERT INTO _Country(IsoCode, Name) VALUES ('AE', 'United Arab Emirates');
INSERT INTO _Country(IsoCode, Name) VALUES ('GB', 'United Kingdom');
INSERT INTO _Country(IsoCode, Name) VALUES ('US', 'United States');

----------------------------------------------------------------------
select * from _Country