//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentAppartment.Client.RApmentAdminService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuthenticationRequest", Namespace="http://schemas.datacontract.org/2004/07/RentApartment.Service.DataContract.Reques" +
        "t")]
    [System.SerializableAttribute()]
    public partial class AuthenticationRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Login {
            get {
                return this.LoginField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginField, value) != true)) {
                    this.LoginField = value;
                    this.RaisePropertyChanged("Login");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseResponse", Namespace="http://schemas.datacontract.org/2004/07/RentApartment.Service.DataContract.Respon" +
        "se")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RentAppartment.Client.RApmentAdminService.GetPropertyListingResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RentAppartment.Client.RApmentAdminService.GetReservationsResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RentAppartment.Client.RApmentAdminService.GetAccountsResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RentAppartment.Client.RApmentAdminService.GetDictionaryDataResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RentAppartment.Client.RApmentAdminService.AmenitiesResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RentAppartment.Client.RApmentAdminService.GetApartmentReservationsResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RentAppartment.Client.RApmentAdminService.AuthenticationResponse))]
    public partial class BaseResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorDescField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ErrorIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorDesc {
            get {
                return this.ErrorDescField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorDescField, value) != true)) {
                    this.ErrorDescField = value;
                    this.RaisePropertyChanged("ErrorDesc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ErrorId {
            get {
                return this.ErrorIdField;
            }
            set {
                if ((this.ErrorIdField.Equals(value) != true)) {
                    this.ErrorIdField = value;
                    this.RaisePropertyChanged("ErrorId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetPropertyListingResponse", Namespace="http://schemas.datacontract.org/2004/07/RentApartment.Service.DataContract.Respon" +
        "se")]
    [System.SerializableAttribute()]
    public partial class GetPropertyListingResponse : RentAppartment.Client.RApmentAdminService.BaseResponse {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RentAppartment.Client.RApmentAdminService.PropertyDto[] PropertListingField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RentAppartment.Client.RApmentAdminService.PropertyDto[] PropertListing {
            get {
                return this.PropertListingField;
            }
            set {
                if ((object.ReferenceEquals(this.PropertListingField, value) != true)) {
                    this.PropertListingField = value;
                    this.RaisePropertyChanged("PropertListing");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetReservationsResponse", Namespace="http://schemas.datacontract.org/2004/07/RentApartment.Service.DataContract.Respon" +
        "se")]
    [System.SerializableAttribute()]
    public partial class GetReservationsResponse : RentAppartment.Client.RApmentAdminService.BaseResponse {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RentAppartment.Client.RApmentAdminService.ReservationDto[] ReservationField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RentAppartment.Client.RApmentAdminService.ReservationDto[] Reservation {
            get {
                return this.ReservationField;
            }
            set {
                if ((object.ReferenceEquals(this.ReservationField, value) != true)) {
                    this.ReservationField = value;
                    this.RaisePropertyChanged("Reservation");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetAccountsResponse", Namespace="http://schemas.datacontract.org/2004/07/RentApartment.Service.DataContract.Respon" +
        "se")]
    [System.SerializableAttribute()]
    public partial class GetAccountsResponse : RentAppartment.Client.RApmentAdminService.BaseResponse {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RentAppartment.Client.RApmentAdminService.AccountDto[] AccountsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RentAppartment.Client.RApmentAdminService.AccountDto[] Accounts {
            get {
                return this.AccountsField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountsField, value) != true)) {
                    this.AccountsField = value;
                    this.RaisePropertyChanged("Accounts");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetDictionaryDataResponse", Namespace="http://schemas.datacontract.org/2004/07/RentApartment.Service.DataContract.Respon" +
        "se")]
    [System.SerializableAttribute()]
    public partial class GetDictionaryDataResponse : RentAppartment.Client.RApmentAdminService.BaseResponse {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<int, string> DataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<int, string> Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AmenitiesResponse", Namespace="http://schemas.datacontract.org/2004/07/RentApartment.Service.DataContract.Respon" +
        "se")]
    [System.SerializableAttribute()]
    public partial class AmenitiesResponse : RentAppartment.Client.RApmentAdminService.BaseResponse {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RentAppartment.Client.RApmentAdminService.AmenityDto[] AmenitiesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RentAppartment.Client.RApmentAdminService.AmenityDto[] Amenities {
            get {
                return this.AmenitiesField;
            }
            set {
                if ((object.ReferenceEquals(this.AmenitiesField, value) != true)) {
                    this.AmenitiesField = value;
                    this.RaisePropertyChanged("Amenities");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetApartmentReservationsResponse", Namespace="http://schemas.datacontract.org/2004/07/RentApartment.Service.DataContract.Respon" +
        "se")]
    [System.SerializableAttribute()]
    public partial class GetApartmentReservationsResponse : RentAppartment.Client.RApmentAdminService.BaseResponse {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime[] BlackOutDatesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime[] BlackOutDates {
            get {
                return this.BlackOutDatesField;
            }
            set {
                if ((object.ReferenceEquals(this.BlackOutDatesField, value) != true)) {
                    this.BlackOutDatesField = value;
                    this.RaisePropertyChanged("BlackOutDates");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuthenticationResponse", Namespace="http://schemas.datacontract.org/2004/07/RentApartment.Service.DataContract.Respon" +
        "se")]
    [System.SerializableAttribute()]
    public partial class AuthenticationResponse : RentAppartment.Client.RApmentAdminService.BaseResponse {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RentAppartment.Client.RApmentAdminService.AccountDto AccountProfileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AuthenticationResultField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RentAppartment.Client.RApmentAdminService.AccountDto AccountProfile {
            get {
                return this.AccountProfileField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountProfileField, value) != true)) {
                    this.AccountProfileField = value;
                    this.RaisePropertyChanged("AccountProfile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AuthenticationResult {
            get {
                return this.AuthenticationResultField;
            }
            set {
                if ((this.AuthenticationResultField.Equals(value) != true)) {
                    this.AuthenticationResultField = value;
                    this.RaisePropertyChanged("AuthenticationResult");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccountDto", Namespace="http://schemas.datacontract.org/2004/07/RentApartment.Service.DataContract.Respon" +
        "se")]
    [System.SerializableAttribute()]
    public partial class AccountDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> BirthdayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<byte> GenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GenderNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsEmailConfirmedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsValidatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> LanguageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MobileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordHashField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PictureUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PostalCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte RolesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RolesNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountId {
            get {
                return this.AccountIdField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountIdField, value) != true)) {
                    this.AccountIdField = value;
                    this.RaisePropertyChanged("AccountId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Birthday {
            get {
                return this.BirthdayField;
            }
            set {
                if ((this.BirthdayField.Equals(value) != true)) {
                    this.BirthdayField = value;
                    this.RaisePropertyChanged("Birthday");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Country {
            get {
                return this.CountryField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryField, value) != true)) {
                    this.CountryField = value;
                    this.RaisePropertyChanged("Country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<byte> Gender {
            get {
                return this.GenderField;
            }
            set {
                if ((this.GenderField.Equals(value) != true)) {
                    this.GenderField = value;
                    this.RaisePropertyChanged("Gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GenderName {
            get {
                return this.GenderNameField;
            }
            set {
                if ((object.ReferenceEquals(this.GenderNameField, value) != true)) {
                    this.GenderNameField = value;
                    this.RaisePropertyChanged("GenderName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsEmailConfirmed {
            get {
                return this.IsEmailConfirmedField;
            }
            set {
                if ((this.IsEmailConfirmedField.Equals(value) != true)) {
                    this.IsEmailConfirmedField = value;
                    this.RaisePropertyChanged("IsEmailConfirmed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsValidated {
            get {
                return this.IsValidatedField;
            }
            set {
                if ((this.IsValidatedField.Equals(value) != true)) {
                    this.IsValidatedField = value;
                    this.RaisePropertyChanged("IsValidated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Language {
            get {
                return this.LanguageField;
            }
            set {
                if ((this.LanguageField.Equals(value) != true)) {
                    this.LanguageField = value;
                    this.RaisePropertyChanged("Language");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Login {
            get {
                return this.LoginField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginField, value) != true)) {
                    this.LoginField = value;
                    this.RaisePropertyChanged("Login");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mobile {
            get {
                return this.MobileField;
            }
            set {
                if ((object.ReferenceEquals(this.MobileField, value) != true)) {
                    this.MobileField = value;
                    this.RaisePropertyChanged("Mobile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PasswordHash {
            get {
                return this.PasswordHashField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordHashField, value) != true)) {
                    this.PasswordHashField = value;
                    this.RaisePropertyChanged("PasswordHash");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PictureUrl {
            get {
                return this.PictureUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.PictureUrlField, value) != true)) {
                    this.PictureUrlField = value;
                    this.RaisePropertyChanged("PictureUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PostalCode {
            get {
                return this.PostalCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PostalCodeField, value) != true)) {
                    this.PostalCodeField = value;
                    this.RaisePropertyChanged("PostalCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte Roles {
            get {
                return this.RolesField;
            }
            set {
                if ((this.RolesField.Equals(value) != true)) {
                    this.RolesField = value;
                    this.RaisePropertyChanged("Roles");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RolesName {
            get {
                return this.RolesNameField;
            }
            set {
                if ((object.ReferenceEquals(this.RolesNameField, value) != true)) {
                    this.RolesNameField = value;
                    this.RaisePropertyChanged("RolesName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PropertyDto", Namespace="http://schemas.datacontract.org/2004/07/RentApartment.Service.DataContract.Entiti" +
        "es")]
    [System.SerializableAttribute()]
    public partial class PropertyDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte AccommodatesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RentAppartment.Client.RApmentAdminService.AccountDto AccountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Address1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Address2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BathroomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte BedRoomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RentAppartment.Client.RApmentAdminService.AmenityDto[] C_AmenitiesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FK_AccountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FK__CountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GreatSummaryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GreatTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte HomeTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HomeTypeNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhotosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> PricePerMonthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> PricePerNightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> PricePerWeekField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PropertyIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte RoomTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoomTypeNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte StateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string State2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZipField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte Accommodates {
            get {
                return this.AccommodatesField;
            }
            set {
                if ((this.AccommodatesField.Equals(value) != true)) {
                    this.AccommodatesField = value;
                    this.RaisePropertyChanged("Accommodates");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RentAppartment.Client.RApmentAdminService.AccountDto Account {
            get {
                return this.AccountField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountField, value) != true)) {
                    this.AccountField = value;
                    this.RaisePropertyChanged("Account");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address1 {
            get {
                return this.Address1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Address1Field, value) != true)) {
                    this.Address1Field = value;
                    this.RaisePropertyChanged("Address1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address2 {
            get {
                return this.Address2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Address2Field, value) != true)) {
                    this.Address2Field = value;
                    this.RaisePropertyChanged("Address2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Bathroom {
            get {
                return this.BathroomField;
            }
            set {
                if ((this.BathroomField.Equals(value) != true)) {
                    this.BathroomField = value;
                    this.RaisePropertyChanged("Bathroom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte BedRoom {
            get {
                return this.BedRoomField;
            }
            set {
                if ((this.BedRoomField.Equals(value) != true)) {
                    this.BedRoomField = value;
                    this.RaisePropertyChanged("BedRoom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RentAppartment.Client.RApmentAdminService.AmenityDto[] C_Amenities {
            get {
                return this.C_AmenitiesField;
            }
            set {
                if ((object.ReferenceEquals(this.C_AmenitiesField, value) != true)) {
                    this.C_AmenitiesField = value;
                    this.RaisePropertyChanged("C_Amenities");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Country {
            get {
                return this.CountryField;
            }
            set {
                if ((this.CountryField.Equals(value) != true)) {
                    this.CountryField = value;
                    this.RaisePropertyChanged("Country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FK_Account {
            get {
                return this.FK_AccountField;
            }
            set {
                if ((this.FK_AccountField.Equals(value) != true)) {
                    this.FK_AccountField = value;
                    this.RaisePropertyChanged("FK_Account");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FK__Country {
            get {
                return this.FK__CountryField;
            }
            set {
                if ((this.FK__CountryField.Equals(value) != true)) {
                    this.FK__CountryField = value;
                    this.RaisePropertyChanged("FK__Country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GreatSummary {
            get {
                return this.GreatSummaryField;
            }
            set {
                if ((object.ReferenceEquals(this.GreatSummaryField, value) != true)) {
                    this.GreatSummaryField = value;
                    this.RaisePropertyChanged("GreatSummary");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GreatTitle {
            get {
                return this.GreatTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.GreatTitleField, value) != true)) {
                    this.GreatTitleField = value;
                    this.RaisePropertyChanged("GreatTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte HomeType {
            get {
                return this.HomeTypeField;
            }
            set {
                if ((this.HomeTypeField.Equals(value) != true)) {
                    this.HomeTypeField = value;
                    this.RaisePropertyChanged("HomeType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HomeTypeName {
            get {
                return this.HomeTypeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.HomeTypeNameField, value) != true)) {
                    this.HomeTypeNameField = value;
                    this.RaisePropertyChanged("HomeTypeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Photos {
            get {
                return this.PhotosField;
            }
            set {
                if ((object.ReferenceEquals(this.PhotosField, value) != true)) {
                    this.PhotosField = value;
                    this.RaisePropertyChanged("Photos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> PricePerMonth {
            get {
                return this.PricePerMonthField;
            }
            set {
                if ((this.PricePerMonthField.Equals(value) != true)) {
                    this.PricePerMonthField = value;
                    this.RaisePropertyChanged("PricePerMonth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> PricePerNight {
            get {
                return this.PricePerNightField;
            }
            set {
                if ((this.PricePerNightField.Equals(value) != true)) {
                    this.PricePerNightField = value;
                    this.RaisePropertyChanged("PricePerNight");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> PricePerWeek {
            get {
                return this.PricePerWeekField;
            }
            set {
                if ((this.PricePerWeekField.Equals(value) != true)) {
                    this.PricePerWeekField = value;
                    this.RaisePropertyChanged("PricePerWeek");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PropertyId {
            get {
                return this.PropertyIdField;
            }
            set {
                if ((this.PropertyIdField.Equals(value) != true)) {
                    this.PropertyIdField = value;
                    this.RaisePropertyChanged("PropertyId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte RoomType {
            get {
                return this.RoomTypeField;
            }
            set {
                if ((this.RoomTypeField.Equals(value) != true)) {
                    this.RoomTypeField = value;
                    this.RaisePropertyChanged("RoomType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RoomTypeName {
            get {
                return this.RoomTypeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.RoomTypeNameField, value) != true)) {
                    this.RoomTypeNameField = value;
                    this.RaisePropertyChanged("RoomTypeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte State {
            get {
                return this.StateField;
            }
            set {
                if ((this.StateField.Equals(value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string State2 {
            get {
                return this.State2Field;
            }
            set {
                if ((object.ReferenceEquals(this.State2Field, value) != true)) {
                    this.State2Field = value;
                    this.RaisePropertyChanged("State2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Zip {
            get {
                return this.ZipField;
            }
            set {
                if ((object.ReferenceEquals(this.ZipField, value) != true)) {
                    this.ZipField = value;
                    this.RaisePropertyChanged("Zip");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AmenityDto", Namespace="http://schemas.datacontract.org/2004/07/RentApartment.Service.DataContract.Entiti" +
        "es")]
    [System.SerializableAttribute()]
    public partial class AmenityDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsActive {
            get {
                return this.IsActiveField;
            }
            set {
                if ((this.IsActiveField.Equals(value) != true)) {
                    this.IsActiveField = value;
                    this.RaisePropertyChanged("IsActive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReservationDto", Namespace="http://schemas.datacontract.org/2004/07/RentApartment.Service.DataContract.Respon" +
        "se")]
    [System.SerializableAttribute()]
    public partial class ReservationDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AccountIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CurrencyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RentAppartment.Client.RApmentAdminService.PropertyDto PropertyListingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PropertyListingIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ReservationEndField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ReservationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReservationNoteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ReservationStartField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ReservationStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReservationStatusNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StayingDaysField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TotalPriceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AccountId {
            get {
                return this.AccountIdField;
            }
            set {
                if ((this.AccountIdField.Equals(value) != true)) {
                    this.AccountIdField = value;
                    this.RaisePropertyChanged("AccountId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Currency {
            get {
                return this.CurrencyField;
            }
            set {
                if ((this.CurrencyField.Equals(value) != true)) {
                    this.CurrencyField = value;
                    this.RaisePropertyChanged("Currency");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RentAppartment.Client.RApmentAdminService.PropertyDto PropertyListing {
            get {
                return this.PropertyListingField;
            }
            set {
                if ((object.ReferenceEquals(this.PropertyListingField, value) != true)) {
                    this.PropertyListingField = value;
                    this.RaisePropertyChanged("PropertyListing");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PropertyListingId {
            get {
                return this.PropertyListingIdField;
            }
            set {
                if ((this.PropertyListingIdField.Equals(value) != true)) {
                    this.PropertyListingIdField = value;
                    this.RaisePropertyChanged("PropertyListingId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ReservationEnd {
            get {
                return this.ReservationEndField;
            }
            set {
                if ((this.ReservationEndField.Equals(value) != true)) {
                    this.ReservationEndField = value;
                    this.RaisePropertyChanged("ReservationEnd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ReservationId {
            get {
                return this.ReservationIdField;
            }
            set {
                if ((this.ReservationIdField.Equals(value) != true)) {
                    this.ReservationIdField = value;
                    this.RaisePropertyChanged("ReservationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReservationNote {
            get {
                return this.ReservationNoteField;
            }
            set {
                if ((object.ReferenceEquals(this.ReservationNoteField, value) != true)) {
                    this.ReservationNoteField = value;
                    this.RaisePropertyChanged("ReservationNote");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ReservationStart {
            get {
                return this.ReservationStartField;
            }
            set {
                if ((this.ReservationStartField.Equals(value) != true)) {
                    this.ReservationStartField = value;
                    this.RaisePropertyChanged("ReservationStart");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ReservationStatus {
            get {
                return this.ReservationStatusField;
            }
            set {
                if ((this.ReservationStatusField.Equals(value) != true)) {
                    this.ReservationStatusField = value;
                    this.RaisePropertyChanged("ReservationStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReservationStatusName {
            get {
                return this.ReservationStatusNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ReservationStatusNameField, value) != true)) {
                    this.ReservationStatusNameField = value;
                    this.RaisePropertyChanged("ReservationStatusName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StayingDays {
            get {
                return this.StayingDaysField;
            }
            set {
                if ((this.StayingDaysField.Equals(value) != true)) {
                    this.StayingDaysField = value;
                    this.RaisePropertyChanged("StayingDays");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalPrice {
            get {
                return this.TotalPriceField;
            }
            set {
                if ((this.TotalPriceField.Equals(value) != true)) {
                    this.TotalPriceField = value;
                    this.RaisePropertyChanged("TotalPrice");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PaginationRequest", Namespace="http://schemas.datacontract.org/2004/07/RentApartment.Service.DataContract.Reques" +
        "t")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RentAppartment.Client.RApmentAdminService.GetAccountsRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RentAppartment.Client.RApmentAdminService.GetPropertyListingRequest))]
    public partial class PaginationRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PageIndexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PageSizeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageIndex {
            get {
                return this.PageIndexField;
            }
            set {
                if ((this.PageIndexField.Equals(value) != true)) {
                    this.PageIndexField = value;
                    this.RaisePropertyChanged("PageIndex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageSize {
            get {
                return this.PageSizeField;
            }
            set {
                if ((this.PageSizeField.Equals(value) != true)) {
                    this.PageSizeField = value;
                    this.RaisePropertyChanged("PageSize");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetAccountsRequest", Namespace="http://schemas.datacontract.org/2004/07/RentApartment.Service.DataContract.Reques" +
        "t")]
    [System.SerializableAttribute()]
    public partial class GetAccountsRequest : RentAppartment.Client.RApmentAdminService.PaginationRequest {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> AccountIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> AccountId {
            get {
                return this.AccountIdField;
            }
            set {
                if ((this.AccountIdField.Equals(value) != true)) {
                    this.AccountIdField = value;
                    this.RaisePropertyChanged("AccountId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetPropertyListingRequest", Namespace="http://schemas.datacontract.org/2004/07/RentApartment.Service.DataContract.Reques" +
        "t")]
    [System.SerializableAttribute()]
    public partial class GetPropertyListingRequest : RentAppartment.Client.RApmentAdminService.PaginationRequest {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> HomeTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> OwnerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> PropertyIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> RoomNumbersField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> HomeType {
            get {
                return this.HomeTypeField;
            }
            set {
                if ((this.HomeTypeField.Equals(value) != true)) {
                    this.HomeTypeField = value;
                    this.RaisePropertyChanged("HomeType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> OwnerId {
            get {
                return this.OwnerIdField;
            }
            set {
                if ((this.OwnerIdField.Equals(value) != true)) {
                    this.OwnerIdField = value;
                    this.RaisePropertyChanged("OwnerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> PropertyId {
            get {
                return this.PropertyIdField;
            }
            set {
                if ((this.PropertyIdField.Equals(value) != true)) {
                    this.PropertyIdField = value;
                    this.RaisePropertyChanged("PropertyId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> RoomNumbers {
            get {
                return this.RoomNumbersField;
            }
            set {
                if ((this.RoomNumbersField.Equals(value) != true)) {
                    this.RoomNumbersField = value;
                    this.RaisePropertyChanged("RoomNumbers");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetReservationsRequest", Namespace="http://schemas.datacontract.org/2004/07/RentApartment.Service.DataContract.Reques" +
        "t")]
    [System.SerializableAttribute()]
    public partial class GetReservationsRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> AccountIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ReservationEndField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ReservationStartField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ReservationStatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> AccountId {
            get {
                return this.AccountIdField;
            }
            set {
                if ((this.AccountIdField.Equals(value) != true)) {
                    this.AccountIdField = value;
                    this.RaisePropertyChanged("AccountId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ReservationEnd {
            get {
                return this.ReservationEndField;
            }
            set {
                if ((this.ReservationEndField.Equals(value) != true)) {
                    this.ReservationEndField = value;
                    this.RaisePropertyChanged("ReservationEnd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ReservationStart {
            get {
                return this.ReservationStartField;
            }
            set {
                if ((this.ReservationStartField.Equals(value) != true)) {
                    this.ReservationStartField = value;
                    this.RaisePropertyChanged("ReservationStart");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ReservationStatus {
            get {
                return this.ReservationStatusField;
            }
            set {
                if ((this.ReservationStatusField.Equals(value) != true)) {
                    this.ReservationStatusField = value;
                    this.RaisePropertyChanged("ReservationStatus");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChangeAccountRequest", Namespace="http://schemas.datacontract.org/2004/07/RentApartment.Service.DataContract.Reques" +
        "t")]
    [System.SerializableAttribute()]
    public partial class ChangeAccountRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RentAppartment.Client.RApmentAdminService.AccountDto AccountField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RentAppartment.Client.RApmentAdminService.AccountDto Account {
            get {
                return this.AccountField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountField, value) != true)) {
                    this.AccountField = value;
                    this.RaisePropertyChanged("Account");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChangedPropertyRequest", Namespace="http://schemas.datacontract.org/2004/07/RentApartment.Service.DataContract.Reques" +
        "t")]
    [System.SerializableAttribute()]
    public partial class ChangedPropertyRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RentAppartment.Client.RApmentAdminService.PropertyDto PropertyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RentAppartment.Client.RApmentAdminService.PropertyDto Property {
            get {
                return this.PropertyField;
            }
            set {
                if ((object.ReferenceEquals(this.PropertyField, value) != true)) {
                    this.PropertyField = value;
                    this.RaisePropertyChanged("Property");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RApmentAdminService.IRApmentAdministration")]
    public interface IRApmentAdministration {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRApmentAdministration/Authenticate", ReplyAction="http://tempuri.org/IRApmentAdministration/AuthenticateResponse")]
        RentAppartment.Client.RApmentAdminService.AuthenticationResponse Authenticate(RentAppartment.Client.RApmentAdminService.AuthenticationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRApmentAdministration/Authenticate", ReplyAction="http://tempuri.org/IRApmentAdministration/AuthenticateResponse")]
        System.Threading.Tasks.Task<RentAppartment.Client.RApmentAdminService.AuthenticationResponse> AuthenticateAsync(RentAppartment.Client.RApmentAdminService.AuthenticationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRApmentAdministration/GetPropertyListing", ReplyAction="http://tempuri.org/IRApmentAdministration/GetPropertyListingResponse")]
        RentAppartment.Client.RApmentAdminService.GetPropertyListingResponse GetPropertyListing(RentAppartment.Client.RApmentAdminService.GetPropertyListingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRApmentAdministration/GetPropertyListing", ReplyAction="http://tempuri.org/IRApmentAdministration/GetPropertyListingResponse")]
        System.Threading.Tasks.Task<RentAppartment.Client.RApmentAdminService.GetPropertyListingResponse> GetPropertyListingAsync(RentAppartment.Client.RApmentAdminService.GetPropertyListingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRApmentAdministration/GetReservations", ReplyAction="http://tempuri.org/IRApmentAdministration/GetReservationsResponse")]
        RentAppartment.Client.RApmentAdminService.GetReservationsResponse GetReservations(RentAppartment.Client.RApmentAdminService.GetReservationsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRApmentAdministration/GetReservations", ReplyAction="http://tempuri.org/IRApmentAdministration/GetReservationsResponse")]
        System.Threading.Tasks.Task<RentAppartment.Client.RApmentAdminService.GetReservationsResponse> GetReservationsAsync(RentAppartment.Client.RApmentAdminService.GetReservationsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRApmentAdministration/GetAccounts", ReplyAction="http://tempuri.org/IRApmentAdministration/GetAccountsResponse")]
        RentAppartment.Client.RApmentAdminService.GetAccountsResponse GetAccounts(RentAppartment.Client.RApmentAdminService.GetAccountsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRApmentAdministration/GetAccounts", ReplyAction="http://tempuri.org/IRApmentAdministration/GetAccountsResponse")]
        System.Threading.Tasks.Task<RentAppartment.Client.RApmentAdminService.GetAccountsResponse> GetAccountsAsync(RentAppartment.Client.RApmentAdminService.GetAccountsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRApmentAdministration/CreateAccount", ReplyAction="http://tempuri.org/IRApmentAdministration/CreateAccountResponse")]
        RentAppartment.Client.RApmentAdminService.BaseResponse CreateAccount(RentAppartment.Client.RApmentAdminService.ChangeAccountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRApmentAdministration/CreateAccount", ReplyAction="http://tempuri.org/IRApmentAdministration/CreateAccountResponse")]
        System.Threading.Tasks.Task<RentAppartment.Client.RApmentAdminService.BaseResponse> CreateAccountAsync(RentAppartment.Client.RApmentAdminService.ChangeAccountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRApmentAdministration/UpdateAccount", ReplyAction="http://tempuri.org/IRApmentAdministration/UpdateAccountResponse")]
        RentAppartment.Client.RApmentAdminService.BaseResponse UpdateAccount(RentAppartment.Client.RApmentAdminService.ChangeAccountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRApmentAdministration/UpdateAccount", ReplyAction="http://tempuri.org/IRApmentAdministration/UpdateAccountResponse")]
        System.Threading.Tasks.Task<RentAppartment.Client.RApmentAdminService.BaseResponse> UpdateAccountAsync(RentAppartment.Client.RApmentAdminService.ChangeAccountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRApmentAdministration/RemoveAccount", ReplyAction="http://tempuri.org/IRApmentAdministration/RemoveAccountResponse")]
        RentAppartment.Client.RApmentAdminService.BaseResponse RemoveAccount(int accountId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRApmentAdministration/RemoveAccount", ReplyAction="http://tempuri.org/IRApmentAdministration/RemoveAccountResponse")]
        System.Threading.Tasks.Task<RentAppartment.Client.RApmentAdminService.BaseResponse> RemoveAccountAsync(int accountId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRApmentAdministration/GetHomeType", ReplyAction="http://tempuri.org/IRApmentAdministration/GetHomeTypeResponse")]
        RentAppartment.Client.RApmentAdminService.GetDictionaryDataResponse GetHomeType();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRApmentAdministration/GetHomeType", ReplyAction="http://tempuri.org/IRApmentAdministration/GetHomeTypeResponse")]
        System.Threading.Tasks.Task<RentAppartment.Client.RApmentAdminService.GetDictionaryDataResponse> GetHomeTypeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRApmentAdministration/GetRoomType", ReplyAction="http://tempuri.org/IRApmentAdministration/GetRoomTypeResponse")]
        RentAppartment.Client.RApmentAdminService.GetDictionaryDataResponse GetRoomType();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRApmentAdministration/GetRoomType", ReplyAction="http://tempuri.org/IRApmentAdministration/GetRoomTypeResponse")]
        System.Threading.Tasks.Task<RentAppartment.Client.RApmentAdminService.GetDictionaryDataResponse> GetRoomTypeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRApmentAdministration/GetUserRole", ReplyAction="http://tempuri.org/IRApmentAdministration/GetUserRoleResponse")]
        RentAppartment.Client.RApmentAdminService.GetDictionaryDataResponse GetUserRole();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRApmentAdministration/GetUserRole", ReplyAction="http://tempuri.org/IRApmentAdministration/GetUserRoleResponse")]
        System.Threading.Tasks.Task<RentAppartment.Client.RApmentAdminService.GetDictionaryDataResponse> GetUserRoleAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRApmentAdministration/GetGender", ReplyAction="http://tempuri.org/IRApmentAdministration/GetGenderResponse")]
        RentAppartment.Client.RApmentAdminService.GetDictionaryDataResponse GetGender();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRApmentAdministration/GetGender", ReplyAction="http://tempuri.org/IRApmentAdministration/GetGenderResponse")]
        System.Threading.Tasks.Task<RentAppartment.Client.RApmentAdminService.GetDictionaryDataResponse> GetGenderAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRApmentAdministration/GetAmenities", ReplyAction="http://tempuri.org/IRApmentAdministration/GetAmenitiesResponse")]
        RentAppartment.Client.RApmentAdminService.AmenitiesResponse GetAmenities();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRApmentAdministration/GetAmenities", ReplyAction="http://tempuri.org/IRApmentAdministration/GetAmenitiesResponse")]
        System.Threading.Tasks.Task<RentAppartment.Client.RApmentAdminService.AmenitiesResponse> GetAmenitiesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRApmentAdministration/GetApartmentReservation", ReplyAction="http://tempuri.org/IRApmentAdministration/GetApartmentReservationResponse")]
        RentAppartment.Client.RApmentAdminService.GetApartmentReservationsResponse GetApartmentReservation(int propertyId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRApmentAdministration/GetApartmentReservation", ReplyAction="http://tempuri.org/IRApmentAdministration/GetApartmentReservationResponse")]
        System.Threading.Tasks.Task<RentAppartment.Client.RApmentAdminService.GetApartmentReservationsResponse> GetApartmentReservationAsync(int propertyId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRApmentAdministration/MakeApartmentReservation", ReplyAction="http://tempuri.org/IRApmentAdministration/MakeApartmentReservationResponse")]
        RentAppartment.Client.RApmentAdminService.BaseResponse MakeApartmentReservation(int accountId, int propertyId, System.DateTime startDate, System.DateTime endDate, string note);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRApmentAdministration/MakeApartmentReservation", ReplyAction="http://tempuri.org/IRApmentAdministration/MakeApartmentReservationResponse")]
        System.Threading.Tasks.Task<RentAppartment.Client.RApmentAdminService.BaseResponse> MakeApartmentReservationAsync(int accountId, int propertyId, System.DateTime startDate, System.DateTime endDate, string note);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRApmentAdministration/CreateProperty", ReplyAction="http://tempuri.org/IRApmentAdministration/CreatePropertyResponse")]
        RentAppartment.Client.RApmentAdminService.BaseResponse CreateProperty(RentAppartment.Client.RApmentAdminService.ChangedPropertyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRApmentAdministration/CreateProperty", ReplyAction="http://tempuri.org/IRApmentAdministration/CreatePropertyResponse")]
        System.Threading.Tasks.Task<RentAppartment.Client.RApmentAdminService.BaseResponse> CreatePropertyAsync(RentAppartment.Client.RApmentAdminService.ChangedPropertyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRApmentAdministration/UpdateProperty", ReplyAction="http://tempuri.org/IRApmentAdministration/UpdatePropertyResponse")]
        RentAppartment.Client.RApmentAdminService.BaseResponse UpdateProperty(RentAppartment.Client.RApmentAdminService.ChangedPropertyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRApmentAdministration/UpdateProperty", ReplyAction="http://tempuri.org/IRApmentAdministration/UpdatePropertyResponse")]
        System.Threading.Tasks.Task<RentAppartment.Client.RApmentAdminService.BaseResponse> UpdatePropertyAsync(RentAppartment.Client.RApmentAdminService.ChangedPropertyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRApmentAdministration/RemoveProperty", ReplyAction="http://tempuri.org/IRApmentAdministration/RemovePropertyResponse")]
        RentAppartment.Client.RApmentAdminService.BaseResponse RemoveProperty(int propertyId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRApmentAdministration/RemoveProperty", ReplyAction="http://tempuri.org/IRApmentAdministration/RemovePropertyResponse")]
        System.Threading.Tasks.Task<RentAppartment.Client.RApmentAdminService.BaseResponse> RemovePropertyAsync(int propertyId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRApmentAdministration/GetBookedPropertyByAccount", ReplyAction="http://tempuri.org/IRApmentAdministration/GetBookedPropertyByAccountResponse")]
        RentAppartment.Client.RApmentAdminService.GetPropertyListingResponse GetBookedPropertyByAccount(int accountId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRApmentAdministration/GetBookedPropertyByAccount", ReplyAction="http://tempuri.org/IRApmentAdministration/GetBookedPropertyByAccountResponse")]
        System.Threading.Tasks.Task<RentAppartment.Client.RApmentAdminService.GetPropertyListingResponse> GetBookedPropertyByAccountAsync(int accountId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRApmentAdministration/GetPropertyByAccount", ReplyAction="http://tempuri.org/IRApmentAdministration/GetPropertyByAccountResponse")]
        RentAppartment.Client.RApmentAdminService.GetPropertyListingResponse GetPropertyByAccount(int accountId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRApmentAdministration/GetPropertyByAccount", ReplyAction="http://tempuri.org/IRApmentAdministration/GetPropertyByAccountResponse")]
        System.Threading.Tasks.Task<RentAppartment.Client.RApmentAdminService.GetPropertyListingResponse> GetPropertyByAccountAsync(int accountId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRApmentAdministration/AddPropertyReview", ReplyAction="http://tempuri.org/IRApmentAdministration/AddPropertyReviewResponse")]
        RentAppartment.Client.RApmentAdminService.BaseResponse AddPropertyReview(int propertyId, int accountId, int score, string reviewNotes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRApmentAdministration/AddPropertyReview", ReplyAction="http://tempuri.org/IRApmentAdministration/AddPropertyReviewResponse")]
        System.Threading.Tasks.Task<RentAppartment.Client.RApmentAdminService.BaseResponse> AddPropertyReviewAsync(int propertyId, int accountId, int score, string reviewNotes);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRApmentAdministrationChannel : RentAppartment.Client.RApmentAdminService.IRApmentAdministration, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RApmentAdministrationClient : System.ServiceModel.ClientBase<RentAppartment.Client.RApmentAdminService.IRApmentAdministration>, RentAppartment.Client.RApmentAdminService.IRApmentAdministration {
        
        public RApmentAdministrationClient() {
        }
        
        public RApmentAdministrationClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RApmentAdministrationClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RApmentAdministrationClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RApmentAdministrationClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public RentAppartment.Client.RApmentAdminService.AuthenticationResponse Authenticate(RentAppartment.Client.RApmentAdminService.AuthenticationRequest request) {
            return base.Channel.Authenticate(request);
        }
        
        public System.Threading.Tasks.Task<RentAppartment.Client.RApmentAdminService.AuthenticationResponse> AuthenticateAsync(RentAppartment.Client.RApmentAdminService.AuthenticationRequest request) {
            return base.Channel.AuthenticateAsync(request);
        }
        
        public RentAppartment.Client.RApmentAdminService.GetPropertyListingResponse GetPropertyListing(RentAppartment.Client.RApmentAdminService.GetPropertyListingRequest request) {
            return base.Channel.GetPropertyListing(request);
        }
        
        public System.Threading.Tasks.Task<RentAppartment.Client.RApmentAdminService.GetPropertyListingResponse> GetPropertyListingAsync(RentAppartment.Client.RApmentAdminService.GetPropertyListingRequest request) {
            return base.Channel.GetPropertyListingAsync(request);
        }
        
        public RentAppartment.Client.RApmentAdminService.GetReservationsResponse GetReservations(RentAppartment.Client.RApmentAdminService.GetReservationsRequest request) {
            return base.Channel.GetReservations(request);
        }
        
        public System.Threading.Tasks.Task<RentAppartment.Client.RApmentAdminService.GetReservationsResponse> GetReservationsAsync(RentAppartment.Client.RApmentAdminService.GetReservationsRequest request) {
            return base.Channel.GetReservationsAsync(request);
        }
        
        public RentAppartment.Client.RApmentAdminService.GetAccountsResponse GetAccounts(RentAppartment.Client.RApmentAdminService.GetAccountsRequest request) {
            return base.Channel.GetAccounts(request);
        }
        
        public System.Threading.Tasks.Task<RentAppartment.Client.RApmentAdminService.GetAccountsResponse> GetAccountsAsync(RentAppartment.Client.RApmentAdminService.GetAccountsRequest request) {
            return base.Channel.GetAccountsAsync(request);
        }
        
        public RentAppartment.Client.RApmentAdminService.BaseResponse CreateAccount(RentAppartment.Client.RApmentAdminService.ChangeAccountRequest request) {
            return base.Channel.CreateAccount(request);
        }
        
        public System.Threading.Tasks.Task<RentAppartment.Client.RApmentAdminService.BaseResponse> CreateAccountAsync(RentAppartment.Client.RApmentAdminService.ChangeAccountRequest request) {
            return base.Channel.CreateAccountAsync(request);
        }
        
        public RentAppartment.Client.RApmentAdminService.BaseResponse UpdateAccount(RentAppartment.Client.RApmentAdminService.ChangeAccountRequest request) {
            return base.Channel.UpdateAccount(request);
        }
        
        public System.Threading.Tasks.Task<RentAppartment.Client.RApmentAdminService.BaseResponse> UpdateAccountAsync(RentAppartment.Client.RApmentAdminService.ChangeAccountRequest request) {
            return base.Channel.UpdateAccountAsync(request);
        }
        
        public RentAppartment.Client.RApmentAdminService.BaseResponse RemoveAccount(int accountId) {
            return base.Channel.RemoveAccount(accountId);
        }
        
        public System.Threading.Tasks.Task<RentAppartment.Client.RApmentAdminService.BaseResponse> RemoveAccountAsync(int accountId) {
            return base.Channel.RemoveAccountAsync(accountId);
        }
        
        public RentAppartment.Client.RApmentAdminService.GetDictionaryDataResponse GetHomeType() {
            return base.Channel.GetHomeType();
        }
        
        public System.Threading.Tasks.Task<RentAppartment.Client.RApmentAdminService.GetDictionaryDataResponse> GetHomeTypeAsync() {
            return base.Channel.GetHomeTypeAsync();
        }
        
        public RentAppartment.Client.RApmentAdminService.GetDictionaryDataResponse GetRoomType() {
            return base.Channel.GetRoomType();
        }
        
        public System.Threading.Tasks.Task<RentAppartment.Client.RApmentAdminService.GetDictionaryDataResponse> GetRoomTypeAsync() {
            return base.Channel.GetRoomTypeAsync();
        }
        
        public RentAppartment.Client.RApmentAdminService.GetDictionaryDataResponse GetUserRole() {
            return base.Channel.GetUserRole();
        }
        
        public System.Threading.Tasks.Task<RentAppartment.Client.RApmentAdminService.GetDictionaryDataResponse> GetUserRoleAsync() {
            return base.Channel.GetUserRoleAsync();
        }
        
        public RentAppartment.Client.RApmentAdminService.GetDictionaryDataResponse GetGender() {
            return base.Channel.GetGender();
        }
        
        public System.Threading.Tasks.Task<RentAppartment.Client.RApmentAdminService.GetDictionaryDataResponse> GetGenderAsync() {
            return base.Channel.GetGenderAsync();
        }
        
        public RentAppartment.Client.RApmentAdminService.AmenitiesResponse GetAmenities() {
            return base.Channel.GetAmenities();
        }
        
        public System.Threading.Tasks.Task<RentAppartment.Client.RApmentAdminService.AmenitiesResponse> GetAmenitiesAsync() {
            return base.Channel.GetAmenitiesAsync();
        }
        
        public RentAppartment.Client.RApmentAdminService.GetApartmentReservationsResponse GetApartmentReservation(int propertyId) {
            return base.Channel.GetApartmentReservation(propertyId);
        }
        
        public System.Threading.Tasks.Task<RentAppartment.Client.RApmentAdminService.GetApartmentReservationsResponse> GetApartmentReservationAsync(int propertyId) {
            return base.Channel.GetApartmentReservationAsync(propertyId);
        }
        
        public RentAppartment.Client.RApmentAdminService.BaseResponse MakeApartmentReservation(int accountId, int propertyId, System.DateTime startDate, System.DateTime endDate, string note) {
            return base.Channel.MakeApartmentReservation(accountId, propertyId, startDate, endDate, note);
        }
        
        public System.Threading.Tasks.Task<RentAppartment.Client.RApmentAdminService.BaseResponse> MakeApartmentReservationAsync(int accountId, int propertyId, System.DateTime startDate, System.DateTime endDate, string note) {
            return base.Channel.MakeApartmentReservationAsync(accountId, propertyId, startDate, endDate, note);
        }
        
        public RentAppartment.Client.RApmentAdminService.BaseResponse CreateProperty(RentAppartment.Client.RApmentAdminService.ChangedPropertyRequest request) {
            return base.Channel.CreateProperty(request);
        }
        
        public System.Threading.Tasks.Task<RentAppartment.Client.RApmentAdminService.BaseResponse> CreatePropertyAsync(RentAppartment.Client.RApmentAdminService.ChangedPropertyRequest request) {
            return base.Channel.CreatePropertyAsync(request);
        }
        
        public RentAppartment.Client.RApmentAdminService.BaseResponse UpdateProperty(RentAppartment.Client.RApmentAdminService.ChangedPropertyRequest request) {
            return base.Channel.UpdateProperty(request);
        }
        
        public System.Threading.Tasks.Task<RentAppartment.Client.RApmentAdminService.BaseResponse> UpdatePropertyAsync(RentAppartment.Client.RApmentAdminService.ChangedPropertyRequest request) {
            return base.Channel.UpdatePropertyAsync(request);
        }
        
        public RentAppartment.Client.RApmentAdminService.BaseResponse RemoveProperty(int propertyId) {
            return base.Channel.RemoveProperty(propertyId);
        }
        
        public System.Threading.Tasks.Task<RentAppartment.Client.RApmentAdminService.BaseResponse> RemovePropertyAsync(int propertyId) {
            return base.Channel.RemovePropertyAsync(propertyId);
        }
        
        public RentAppartment.Client.RApmentAdminService.GetPropertyListingResponse GetBookedPropertyByAccount(int accountId) {
            return base.Channel.GetBookedPropertyByAccount(accountId);
        }
        
        public System.Threading.Tasks.Task<RentAppartment.Client.RApmentAdminService.GetPropertyListingResponse> GetBookedPropertyByAccountAsync(int accountId) {
            return base.Channel.GetBookedPropertyByAccountAsync(accountId);
        }
        
        public RentAppartment.Client.RApmentAdminService.GetPropertyListingResponse GetPropertyByAccount(int accountId) {
            return base.Channel.GetPropertyByAccount(accountId);
        }
        
        public System.Threading.Tasks.Task<RentAppartment.Client.RApmentAdminService.GetPropertyListingResponse> GetPropertyByAccountAsync(int accountId) {
            return base.Channel.GetPropertyByAccountAsync(accountId);
        }
        
        public RentAppartment.Client.RApmentAdminService.BaseResponse AddPropertyReview(int propertyId, int accountId, int score, string reviewNotes) {
            return base.Channel.AddPropertyReview(propertyId, accountId, score, reviewNotes);
        }
        
        public System.Threading.Tasks.Task<RentAppartment.Client.RApmentAdminService.BaseResponse> AddPropertyReviewAsync(int propertyId, int accountId, int score, string reviewNotes) {
            return base.Channel.AddPropertyReviewAsync(propertyId, accountId, score, reviewNotes);
        }
    }
}
