<?xml version="1.0" encoding="utf-8"?><Database Name="RentApartments" Class="RApmentModell2sqlDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.\sqlexpress;Initial Catalog=RentApartments;Integrated Security=True;MultipleActiveResultSets=True;Application Name=EntityFramework" SettingsObjectName="RentApartment.Core.Properties.Settings" SettingsPropertyName="RentApartmentsConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Reservations" Member="Reservations">
    <Type Name="Reservation">
      <Column Name="ReservationId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FK_Account" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FK_PropertyListing" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ReservationStatus" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ReservationStart" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ReservationEnd" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ReservationNote" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="FK__Currency" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="_Currency_Reservation" Member="_Currency" ThisKey="FK__Currency" OtherKey="Id" Type="_Currency" IsForeignKey="true" />
      <Association Name="Account_Reservation" Member="Account" ThisKey="FK_Account" OtherKey="id" Type="Account" IsForeignKey="true" />
      <Association Name="PropertyListing_Reservation" Member="PropertyListing" ThisKey="FK_PropertyListing" OtherKey="PropertyId" Type="PropertyListing" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.[_Amenities]" Member="_Amenities">
    <Type Name="_Amenity">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="_Amenity_PropertyListing__Amenity" Member="PropertyListing__Amenities" ThisKey="id" OtherKey="FK__Amenities" Type="PropertyListing__Amenity" />
    </Type>
  </Table>
  <Table Name="dbo.[_Country]" Member="_Countries">
    <Type Name="_Country">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IsoCode" Type="System.String" DbType="VarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Association Name="_Country_Account" Member="Accounts" ThisKey="id" OtherKey="FK__Country" Type="Account" />
      <Association Name="_Country_PropertyListing" Member="PropertyListings" ThisKey="id" OtherKey="FK__Country" Type="PropertyListing" />
    </Type>
  </Table>
  <Table Name="dbo.[_Currency]" Member="_Currencies">
    <Type Name="_Currency">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Country" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Currency" Member="CurrencyName" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="NVarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="Symbol" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Association Name="_Currency_Reservation" Member="Reservations" ThisKey="Id" OtherKey="FK__Currency" Type="Reservation" />
    </Type>
  </Table>
  <Table Name="dbo.[_Roles]" Member="_Roles">
    <Type Name="_Role">
      <Column Name="RoleId" Type="System.Byte" DbType="TinyInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RoleName" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="RoleDescription" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Association Name="_Role_Account" Member="Accounts" ThisKey="RoleId" OtherKey="FK__Roles" Type="Account" />
    </Type>
  </Table>
  <Table Name="dbo.Account" Member="Accounts">
    <Type Name="Account">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AccountId" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="PasswordHash" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="IsEmailConfirmed" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="FK__Country" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FK__Roles" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="City" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Mobile" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="Gender" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="PostalCode" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Language" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsValidated" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ImageSourceId" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Association Name="Account_Reservation" Member="Reservations" ThisKey="id" OtherKey="FK_Account" Type="Reservation" />
      <Association Name="Account_GuestReview" Member="GuestReviews" ThisKey="id" OtherKey="FK_Account" Type="GuestReview" />
      <Association Name="Account_Message" Member="Messages" ThisKey="id" OtherKey="FK_Account" Type="Message" />
      <Association Name="Account_PropertyListing" Member="PropertyListings" ThisKey="id" OtherKey="FK_Account" Type="PropertyListing" />
      <Association Name="_Country_Account" Member="_Country" ThisKey="FK__Country" OtherKey="id" Type="_Country" IsForeignKey="true" />
      <Association Name="_Role_Account" Member="_Role" ThisKey="FK__Roles" OtherKey="RoleId" Type="_Role" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.GuestReviews" Member="GuestReviews">
    <Type Name="GuestReview">
      <Column Name="ReviewId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FK_Account" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FK_PropertyListing" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Review" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="RatingScore" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Account_GuestReview" Member="Account" ThisKey="FK_Account" OtherKey="id" Type="Account" IsForeignKey="true" />
      <Association Name="PropertyListing_GuestReview" Member="PropertyListing" ThisKey="FK_PropertyListing" OtherKey="PropertyId" Type="PropertyListing" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Messages" Member="Messages">
    <Type Name="Message">
      <Column Name="MessageId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MessageType" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="MessageStatus" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="MessageBody" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="FK_Account" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Account_Message" Member="Account" ThisKey="FK_Account" OtherKey="id" Type="Account" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PropertyListing" Member="PropertyListings">
    <Type Name="PropertyListing">
      <Column Name="PropertyId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FK_Account" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="State" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="PricePerNight" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="PricePerMonth" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="PricePerWeek" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Photos" Type="System.String" DbType="NVarChar(2000)" CanBeNull="true" />
      <Column Name="GreatTitle" Type="System.String" DbType="NVarChar(40)" CanBeNull="true" />
      <Column Name="GreatSummary" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="BedRoom" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Bathroom" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="HomeType" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="RoomType" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Accommodates" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Address1" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Address2" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="State2" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Zip" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="FK__Country" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="PropertyListing_Reservation" Member="Reservations" ThisKey="PropertyId" OtherKey="FK_PropertyListing" Type="Reservation" />
      <Association Name="PropertyListing_GuestReview" Member="GuestReviews" ThisKey="PropertyId" OtherKey="FK_PropertyListing" Type="GuestReview" />
      <Association Name="PropertyListing_PropertyListing__Amenity" Member="PropertyListing__Amenities" ThisKey="PropertyId" OtherKey="FK_PropertyListing" Type="PropertyListing__Amenity" />
      <Association Name="Account_PropertyListing" Member="Account" ThisKey="FK_Account" OtherKey="id" Type="Account" IsForeignKey="true" />
      <Association Name="_Country_PropertyListing" Member="_Country" ThisKey="FK__Country" OtherKey="id" Type="_Country" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PropertyListing__Amenities" Member="PropertyListing__Amenities">
    <Type Name="PropertyListing__Amenity">
      <Column Name="FK_PropertyListing" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="FK__Amenities" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="_Amenity_PropertyListing__Amenity" Member="_Amenity" ThisKey="FK__Amenities" OtherKey="id" Type="_Amenity" IsForeignKey="true" />
      <Association Name="PropertyListing_PropertyListing__Amenity" Member="PropertyListing" ThisKey="FK_PropertyListing" OtherKey="PropertyId" Type="PropertyListing" IsForeignKey="true" />
    </Type>
  </Table>
</Database>