//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentApartment.Core.Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Country
    {
        public C_Country()
        {
            this.Account = new HashSet<Account>();
            this.PropertyListing = new HashSet<PropertyListing>();
        }
    
        public int id { get; set; }
        public string IsoCode { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Account> Account { get; set; }
        public virtual ICollection<PropertyListing> PropertyListing { get; set; }
    }
}
