//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentApartment.Core.Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Currency
    {
        public C_Currency()
        {
            this.Reservations = new HashSet<Reservations>();
        }
    
        public int Id { get; set; }
        public string Country { get; set; }
        public string Currency { get; set; }
        public string Code { get; set; }
        public string Symbol { get; set; }
    
        public virtual ICollection<Reservations> Reservations { get; set; }
    }
}
