//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentApartment.Core.Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DB_Errors_Log
    {
        public long DBERRL_ID { get; set; }
        public System.DateTime DBERRL_DateTime { get; set; }
        public Nullable<int> DBERRL_ErrCode { get; set; }
        public string DBERRL_ErrMsg { get; set; }
        public Nullable<int> DBERRL_Severity { get; set; }
        public string DBERRL_APP { get; set; }
        public string DBERRL_Server { get; set; }
        public string DBERRL_DB { get; set; }
        public string DBERRL_SP { get; set; }
        public string DBERRL_USER { get; set; }
        public string DBERRL_HOST { get; set; }
        public Nullable<int> DBERRL_LineNumber { get; set; }
        public Nullable<int> DBERRL_NativeErrCode { get; set; }
        public string DBERR_InstanceName { get; set; }
    }
}
