//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentApartment.Core.Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class GuestReviews
    {
        public int ReviewId { get; set; }
        public int FK_Account { get; set; }
        public int FK_PropertyListing { get; set; }
        public string Review { get; set; }
        public int RatingScore { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual PropertyListing PropertyListing { get; set; }
    }
}
