//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentApartment.Core.Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Messages
    {
        public int MessageId { get; set; }
        public byte MessageType { get; set; }
        public byte MessageStatus { get; set; }
        public string MessageBody { get; set; }
        public int FK_Account { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
