//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabWPF.RApmentAdministrationService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetPropertiesRequest", Namespace="http://schemas.datacontract.org/2004/07/RentApartment.Service.DataContract.Reques" +
        "t")]
    [System.SerializableAttribute()]
    public partial class GetPropertiesRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> AccountIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CountryField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> AccountId {
            get {
                return this.AccountIdField;
            }
            set {
                if ((this.AccountIdField.Equals(value) != true)) {
                    this.AccountIdField = value;
                    this.RaisePropertyChanged("AccountId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Country {
            get {
                return this.CountryField;
            }
            set {
                if ((this.CountryField.Equals(value) != true)) {
                    this.CountryField = value;
                    this.RaisePropertyChanged("Country");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseResponse", Namespace="http://schemas.datacontract.org/2004/07/RentApartment.Service.DataContract.Respon" +
        "se")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LabWPF.RApmentAdministrationService.GetReservationsResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LabWPF.RApmentAdministrationService.GetPropertiesResponse))]
    public partial class BaseResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorDescField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ErrorIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorDesc {
            get {
                return this.ErrorDescField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorDescField, value) != true)) {
                    this.ErrorDescField = value;
                    this.RaisePropertyChanged("ErrorDesc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ErrorId {
            get {
                return this.ErrorIdField;
            }
            set {
                if ((this.ErrorIdField.Equals(value) != true)) {
                    this.ErrorIdField = value;
                    this.RaisePropertyChanged("ErrorId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetReservationsResponse", Namespace="http://schemas.datacontract.org/2004/07/RentApartment.Service.DataContract.Respon" +
        "se")]
    [System.SerializableAttribute()]
    public partial class GetReservationsResponse : LabWPF.RApmentAdministrationService.BaseResponse {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LabWPF.RApmentAdministrationService.Reservation[] ReservationField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LabWPF.RApmentAdministrationService.Reservation[] Reservation {
            get {
                return this.ReservationField;
            }
            set {
                if ((object.ReferenceEquals(this.ReservationField, value) != true)) {
                    this.ReservationField = value;
                    this.RaisePropertyChanged("Reservation");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetPropertiesResponse", Namespace="http://schemas.datacontract.org/2004/07/RentApartment.Service.DataContract.Respon" +
        "se")]
    [System.SerializableAttribute()]
    public partial class GetPropertiesResponse : LabWPF.RApmentAdministrationService.BaseResponse {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LabWPF.RApmentAdministrationService.Property[] PropertiesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LabWPF.RApmentAdministrationService.Property[] Properties {
            get {
                return this.PropertiesField;
            }
            set {
                if ((object.ReferenceEquals(this.PropertiesField, value) != true)) {
                    this.PropertiesField = value;
                    this.RaisePropertyChanged("Properties");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Property", Namespace="http://schemas.datacontract.org/2004/07/RentApartment.Service.DataContract.Entiti" +
        "es")]
    [System.SerializableAttribute()]
    public partial class Property : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte AccommodatesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AccountIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Address1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Address2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BathroomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte BedRoomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GreatSummaryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GreatTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte HomeTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhotosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> PricePerMonthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> PricePerNightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> PricePerWeekField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PropertyIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte RoomTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte StateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string State2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZipField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte Accommodates {
            get {
                return this.AccommodatesField;
            }
            set {
                if ((this.AccommodatesField.Equals(value) != true)) {
                    this.AccommodatesField = value;
                    this.RaisePropertyChanged("Accommodates");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AccountId {
            get {
                return this.AccountIdField;
            }
            set {
                if ((this.AccountIdField.Equals(value) != true)) {
                    this.AccountIdField = value;
                    this.RaisePropertyChanged("AccountId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address1 {
            get {
                return this.Address1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Address1Field, value) != true)) {
                    this.Address1Field = value;
                    this.RaisePropertyChanged("Address1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address2 {
            get {
                return this.Address2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Address2Field, value) != true)) {
                    this.Address2Field = value;
                    this.RaisePropertyChanged("Address2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Bathroom {
            get {
                return this.BathroomField;
            }
            set {
                if ((this.BathroomField.Equals(value) != true)) {
                    this.BathroomField = value;
                    this.RaisePropertyChanged("Bathroom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte BedRoom {
            get {
                return this.BedRoomField;
            }
            set {
                if ((this.BedRoomField.Equals(value) != true)) {
                    this.BedRoomField = value;
                    this.RaisePropertyChanged("BedRoom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Country {
            get {
                return this.CountryField;
            }
            set {
                if ((this.CountryField.Equals(value) != true)) {
                    this.CountryField = value;
                    this.RaisePropertyChanged("Country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GreatSummary {
            get {
                return this.GreatSummaryField;
            }
            set {
                if ((object.ReferenceEquals(this.GreatSummaryField, value) != true)) {
                    this.GreatSummaryField = value;
                    this.RaisePropertyChanged("GreatSummary");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GreatTitle {
            get {
                return this.GreatTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.GreatTitleField, value) != true)) {
                    this.GreatTitleField = value;
                    this.RaisePropertyChanged("GreatTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte HomeType {
            get {
                return this.HomeTypeField;
            }
            set {
                if ((this.HomeTypeField.Equals(value) != true)) {
                    this.HomeTypeField = value;
                    this.RaisePropertyChanged("HomeType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Photos {
            get {
                return this.PhotosField;
            }
            set {
                if ((object.ReferenceEquals(this.PhotosField, value) != true)) {
                    this.PhotosField = value;
                    this.RaisePropertyChanged("Photos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> PricePerMonth {
            get {
                return this.PricePerMonthField;
            }
            set {
                if ((this.PricePerMonthField.Equals(value) != true)) {
                    this.PricePerMonthField = value;
                    this.RaisePropertyChanged("PricePerMonth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> PricePerNight {
            get {
                return this.PricePerNightField;
            }
            set {
                if ((this.PricePerNightField.Equals(value) != true)) {
                    this.PricePerNightField = value;
                    this.RaisePropertyChanged("PricePerNight");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> PricePerWeek {
            get {
                return this.PricePerWeekField;
            }
            set {
                if ((this.PricePerWeekField.Equals(value) != true)) {
                    this.PricePerWeekField = value;
                    this.RaisePropertyChanged("PricePerWeek");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PropertyId {
            get {
                return this.PropertyIdField;
            }
            set {
                if ((this.PropertyIdField.Equals(value) != true)) {
                    this.PropertyIdField = value;
                    this.RaisePropertyChanged("PropertyId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte RoomType {
            get {
                return this.RoomTypeField;
            }
            set {
                if ((this.RoomTypeField.Equals(value) != true)) {
                    this.RoomTypeField = value;
                    this.RaisePropertyChanged("RoomType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte State {
            get {
                return this.StateField;
            }
            set {
                if ((this.StateField.Equals(value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string State2 {
            get {
                return this.State2Field;
            }
            set {
                if ((object.ReferenceEquals(this.State2Field, value) != true)) {
                    this.State2Field = value;
                    this.RaisePropertyChanged("State2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Zip {
            get {
                return this.ZipField;
            }
            set {
                if ((object.ReferenceEquals(this.ZipField, value) != true)) {
                    this.ZipField = value;
                    this.RaisePropertyChanged("Zip");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Reservation", Namespace="http://schemas.datacontract.org/2004/07/RentApartment.Service.DataContract.Respon" +
        "se")]
    [System.SerializableAttribute()]
    public partial class Reservation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AccountIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CurrencyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LabWPF.RApmentAdministrationService.Property PropertyItemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PropertyListingIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ReservationEndField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ReservationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReservationNoteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ReservationStartField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ReservationStatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AccountId {
            get {
                return this.AccountIdField;
            }
            set {
                if ((this.AccountIdField.Equals(value) != true)) {
                    this.AccountIdField = value;
                    this.RaisePropertyChanged("AccountId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Currency {
            get {
                return this.CurrencyField;
            }
            set {
                if ((this.CurrencyField.Equals(value) != true)) {
                    this.CurrencyField = value;
                    this.RaisePropertyChanged("Currency");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LabWPF.RApmentAdministrationService.Property PropertyItem {
            get {
                return this.PropertyItemField;
            }
            set {
                if ((object.ReferenceEquals(this.PropertyItemField, value) != true)) {
                    this.PropertyItemField = value;
                    this.RaisePropertyChanged("PropertyItem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PropertyListingId {
            get {
                return this.PropertyListingIdField;
            }
            set {
                if ((this.PropertyListingIdField.Equals(value) != true)) {
                    this.PropertyListingIdField = value;
                    this.RaisePropertyChanged("PropertyListingId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ReservationEnd {
            get {
                return this.ReservationEndField;
            }
            set {
                if ((this.ReservationEndField.Equals(value) != true)) {
                    this.ReservationEndField = value;
                    this.RaisePropertyChanged("ReservationEnd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ReservationId {
            get {
                return this.ReservationIdField;
            }
            set {
                if ((this.ReservationIdField.Equals(value) != true)) {
                    this.ReservationIdField = value;
                    this.RaisePropertyChanged("ReservationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReservationNote {
            get {
                return this.ReservationNoteField;
            }
            set {
                if ((object.ReferenceEquals(this.ReservationNoteField, value) != true)) {
                    this.ReservationNoteField = value;
                    this.RaisePropertyChanged("ReservationNote");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ReservationStart {
            get {
                return this.ReservationStartField;
            }
            set {
                if ((this.ReservationStartField.Equals(value) != true)) {
                    this.ReservationStartField = value;
                    this.RaisePropertyChanged("ReservationStart");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ReservationStatus {
            get {
                return this.ReservationStatusField;
            }
            set {
                if ((this.ReservationStatusField.Equals(value) != true)) {
                    this.ReservationStatusField = value;
                    this.RaisePropertyChanged("ReservationStatus");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetReservationsRequest", Namespace="http://schemas.datacontract.org/2004/07/RentApartment.Service.DataContract.Reques" +
        "t")]
    [System.SerializableAttribute()]
    public partial class GetReservationsRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ReservationEndField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ReservationStartField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ReservationStatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ReservationEnd {
            get {
                return this.ReservationEndField;
            }
            set {
                if ((this.ReservationEndField.Equals(value) != true)) {
                    this.ReservationEndField = value;
                    this.RaisePropertyChanged("ReservationEnd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ReservationStart {
            get {
                return this.ReservationStartField;
            }
            set {
                if ((this.ReservationStartField.Equals(value) != true)) {
                    this.ReservationStartField = value;
                    this.RaisePropertyChanged("ReservationStart");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ReservationStatus {
            get {
                return this.ReservationStatusField;
            }
            set {
                if ((this.ReservationStatusField.Equals(value) != true)) {
                    this.ReservationStatusField = value;
                    this.RaisePropertyChanged("ReservationStatus");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RApmentAdministrationService.IRApmentAdministration")]
    public interface IRApmentAdministration {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRApmentAdministration/GetProperties", ReplyAction="http://tempuri.org/IRApmentAdministration/GetPropertiesResponse")]
        LabWPF.RApmentAdministrationService.GetPropertiesResponse GetProperties(LabWPF.RApmentAdministrationService.GetPropertiesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRApmentAdministration/GetProperties", ReplyAction="http://tempuri.org/IRApmentAdministration/GetPropertiesResponse")]
        System.Threading.Tasks.Task<LabWPF.RApmentAdministrationService.GetPropertiesResponse> GetPropertiesAsync(LabWPF.RApmentAdministrationService.GetPropertiesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRApmentAdministration/GetReservations", ReplyAction="http://tempuri.org/IRApmentAdministration/GetReservationsResponse")]
        LabWPF.RApmentAdministrationService.GetReservationsResponse GetReservations(LabWPF.RApmentAdministrationService.GetReservationsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRApmentAdministration/GetReservations", ReplyAction="http://tempuri.org/IRApmentAdministration/GetReservationsResponse")]
        System.Threading.Tasks.Task<LabWPF.RApmentAdministrationService.GetReservationsResponse> GetReservationsAsync(LabWPF.RApmentAdministrationService.GetReservationsRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRApmentAdministrationChannel : LabWPF.RApmentAdministrationService.IRApmentAdministration, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RApmentAdministrationClient : System.ServiceModel.ClientBase<LabWPF.RApmentAdministrationService.IRApmentAdministration>, LabWPF.RApmentAdministrationService.IRApmentAdministration {
        
        public RApmentAdministrationClient() {
        }
        
        public RApmentAdministrationClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RApmentAdministrationClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RApmentAdministrationClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RApmentAdministrationClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public LabWPF.RApmentAdministrationService.GetPropertiesResponse GetProperties(LabWPF.RApmentAdministrationService.GetPropertiesRequest request) {
            return base.Channel.GetProperties(request);
        }
        
        public System.Threading.Tasks.Task<LabWPF.RApmentAdministrationService.GetPropertiesResponse> GetPropertiesAsync(LabWPF.RApmentAdministrationService.GetPropertiesRequest request) {
            return base.Channel.GetPropertiesAsync(request);
        }
        
        public LabWPF.RApmentAdministrationService.GetReservationsResponse GetReservations(LabWPF.RApmentAdministrationService.GetReservationsRequest request) {
            return base.Channel.GetReservations(request);
        }
        
        public System.Threading.Tasks.Task<LabWPF.RApmentAdministrationService.GetReservationsResponse> GetReservationsAsync(LabWPF.RApmentAdministrationService.GetReservationsRequest request) {
            return base.Channel.GetReservationsAsync(request);
        }
    }
}
